# Generated by Django 6.0.2 on 2026-02-21 04:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_institucional', models.EmailField(max_length=150, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(db_column='id_rol', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_area', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('director', models.ForeignKey(blank=True, db_column='id_director', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_dirigidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_devolucion_programada', models.DateField(blank=True, null=True)),
                ('fecha_devolucion_real', models.DateTimeField(blank=True, null=True)),
                ('cuatrimestre', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(default='ACTIVO', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alumno', models.ForeignKey(db_column='id_alumno', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asignacion_equipos',
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(db_column='id_area', on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='laboratorios_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'laboratorios',
            },
        ),
        migrations.CreateModel(
            name='HorarioLaboratorio',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=15)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('descripcion_actividad', models.CharField(blank=True, max_length=150, null=True)),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio')),
            ],
            options={
                'db_table': 'horarios_laboratorio',
            },
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('actividad_realizada', models.TextField(blank=True, null=True)),
                ('tipo_actividad', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio')),
            ],
            options={
                'db_table': 'bitacoras',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.TimeField(auto_now_add=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('asignacion_equipo', models.ForeignKey(blank=True, db_column='id_asignacion_equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.asignacionequipo')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio')),
            ],
            options={
                'db_table': 'asistencias',
            },
        ),
        migrations.CreateModel(
            name='Mobiliario',
            fields=[
                ('numero_inventario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_condicion', models.CharField(default='BUENO', max_length=50)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion_especifica', models.CharField(blank=True, max_length=100, null=True)),
                ('detalles_tecnicos', models.JSONField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio')),
            ],
            options={
                'db_table': 'mobiliario',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id_mantenimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_mantenimiento', models.DateField(auto_now_add=True)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('usuario_realizo', models.ForeignKey(blank=True, db_column='id_usuario_realizo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mobiliario', models.ForeignKey(db_column='numero_inventario', on_delete=django.db.models.deletion.CASCADE, to='api.mobiliario')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='asignacionequipo',
            name='mobiliario',
            field=models.ForeignKey(db_column='numero_inventario', on_delete=django.db.models.deletion.RESTRICT, to='api.mobiliario'),
        ),
        migrations.CreateModel(
            name='ReporteFallo',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('detalle_problema', models.TextField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=50)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_resolucion', models.TextField(blank=True, null=True)),
                ('mobiliario', models.ForeignKey(db_column='numero_inventario', on_delete=django.db.models.deletion.CASCADE, to='api.mobiliario')),
                ('usuario_reporta', models.ForeignKey(db_column='id_usuario_reporta', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes_fallos',
            },
        ),
    ]
