# Generated by Django 6.0.2 on 2026-02-23 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
            },
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio'),
        ),
        migrations.AlterField(
            model_name='reportefallo',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN REVISION', 'En revisión'), ('RESUELTO', 'Resuelto'), ('EN MANTENIMIENTO', 'En mantenimiento')], default='PENDIENTE', max_length=50),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_software', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('licencia', models.CharField(blank=True, max_length=100, null=True)),
                ('laboratorios', models.ManyToManyField(db_table='software_laboratorios', related_name='software_instalado', to='api.laboratorio')),
            ],
            options={
                'db_table': 'software',
            },
        ),
    ]
