# Generated by Django 6.0.2 on 2026-02-23 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuracionsistema_alter_bitacora_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportefallo',
            name='urgencia',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=10),
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id_reservacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('materia_grupo', models.CharField(max_length=150)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to='api.laboratorio')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reservaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservaciones',
                'db_table': 'reservaciones',
            },
        ),
    ]
