# Generated by Django 6.0.2 on 2026-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reportefallo_urgencia_reservacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=100),
            preserve_default=False,
        ),
    ]
