# Generated by Django 6.0.2 on 2026-02-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_usuario_first_name_remove_usuario_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='director',
        ),
    ]
