# Generated by Django 6.0.2 on 2026-03-06 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_area_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboratorio',
            name='docente',
            field=models.ForeignKey(blank=True, db_column='id_docente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_clase', to=settings.AUTH_USER_MODEL),
        ),
    ]
