# Generated by Django 6.0.2 on 2026-03-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_horariolaboratorio_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoComputo',
            fields=[
                ('numero_inventario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_condicion', models.CharField(default='BUENO', max_length=50)),
                ('procesador', models.CharField(blank=True, max_length=100, null=True)),
                ('ram', models.CharField(blank=True, max_length=50, null=True)),
                ('disco_duro', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ubicacion_especifica', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, to='api.categoria')),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.RESTRICT, to='api.laboratorio')),
            ],
            options={
                'db_table': 'equipos_computo',
            },
        ),
    ]
