# Generated by Django 6.0.2 on 2026-03-06 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_equipocomputo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionequipo',
            name='equipo_computo',
            field=models.ForeignKey(blank=True, db_column='numero_inventario_pc', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.equipocomputo'),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='equipo_computo',
            field=models.ForeignKey(blank=True, db_column='numero_inventario_pc', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipocomputo'),
        ),
        migrations.AddField(
            model_name='reportefallo',
            name='equipo_computo',
            field=models.ForeignKey(blank=True, db_column='numero_inventario_pc', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipocomputo'),
        ),
        migrations.AlterField(
            model_name='asignacionequipo',
            name='mobiliario',
            field=models.ForeignKey(blank=True, db_column='numero_inventario', null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.mobiliario'),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='mobiliario',
            field=models.ForeignKey(blank=True, db_column='numero_inventario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiliario'),
        ),
        migrations.AlterField(
            model_name='reportefallo',
            name='mobiliario',
            field=models.ForeignKey(blank=True, db_column='numero_inventario', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mobiliario'),
        ),
    ]
