# Generated by Django 6.0.2 on 2026-03-06 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_asignacionequipo_equipo_computo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMobiliario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipos_mobiliario',
            },
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fila', models.IntegerField(default=1)),
                ('columna', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.CASCADE, related_name='estaciones', to='api.laboratorio')),
            ],
            options={
                'db_table': 'estaciones',
                'unique_together': {('nombre', 'laboratorio')},
            },
        ),
        migrations.AddField(
            model_name='equipocomputo',
            name='estacion',
            field=models.ForeignKey(blank=True, db_column='id_estacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipo', to='api.estacion'),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='estacion',
            field=models.ForeignKey(blank=True, db_column='id_estacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perifericos', to='api.estacion'),
        ),
        migrations.AddField(
            model_name='mobiliario',
            name='tipo_mobiliario',
            field=models.ForeignKey(blank=True, db_column='id_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipomobiliario'),
        ),
    ]
