# Generated by Django 6.0.2 on 2026-03-07 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_tipomobiliario_estacion_equipocomputo_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocomputo',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.laboratorio'),
        ),
        migrations.AlterField(
            model_name='mobiliario',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.laboratorio'),
        ),
    ]
