# Generated by Django 6.0.2 on 2026-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_equipocomputo_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='equipos_por_fila',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
