# Generated by Django 6.0.2 on 2026-03-23 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_laboratorio_equipos_por_fila'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='laboratorio',
            field=models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.CASCADE, to='api.laboratorio'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='laboratorio',
            field=models.ForeignKey(blank=True, db_column='id_laboratorio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.laboratorio'),
        ),
    ]
