# Generated by Django 6.0.2 on 2026-03-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_asistencia_laboratorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboratorio',
            name='carrera',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboratorio',
            name='grado',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='horariolaboratorio',
            name='grupo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
