# Generated by Django 6.0.2 on 2026-03-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, default='avatar1', max_length=255, null=True),
        ),
    ]
